/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertType = IDL.Variant({
  'flood' : IDL.Null,
  'earthquake' : IDL.Null,
  'fire' : IDL.Null,
  'tsunami' : IDL.Null,
  'storm' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ID = IDL.Nat;
export const Time = IDL.Int;
export const DisasterAlert = IDL.Record({
  'id' : ID,
  'alertType' : AlertType,
  'message' : IDL.Text,
  'timestamp' : Time,
  'severity' : Severity,
  'location' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'id' : ID,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const SafetyGuideline = IDL.Record({
  'tips' : IDL.Vec(IDL.Text),
  'disasterType' : AlertType,
});
export const SOSEvent = IDL.Record({
  'id' : ID,
  'timestamp' : Time,
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addDisasterAlert' : IDL.Func(
      [AlertType, Severity, IDL.Text, IDL.Text],
      [ID],
      [],
    ),
  'addEmergencyContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ID], []),
  'deleteDisasterAlert' : IDL.Func([ID], [], []),
  'deleteEmergencyContact' : IDL.Func([ID], [], []),
  'getAllDisasterAlerts' : IDL.Func([], [IDL.Vec(DisasterAlert)], ['query']),
  'getAllEmergencyContacts' : IDL.Func(
      [],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getAllSafetyGuidelines' : IDL.Func(
      [],
      [IDL.Vec(SafetyGuideline)],
      ['query'],
    ),
  'getRecentSOSEvents' : IDL.Func([IDL.Nat], [IDL.Vec(SOSEvent)], ['query']),
  'getSafetyGuidelinesByType' : IDL.Func(
      [AlertType],
      [SafetyGuideline],
      ['query'],
    ),
  'logSOSEvent' : IDL.Func([IDL.Opt(IDL.Text)], [ID], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertType = IDL.Variant({
    'flood' : IDL.Null,
    'earthquake' : IDL.Null,
    'fire' : IDL.Null,
    'tsunami' : IDL.Null,
    'storm' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ID = IDL.Nat;
  const Time = IDL.Int;
  const DisasterAlert = IDL.Record({
    'id' : ID,
    'alertType' : AlertType,
    'message' : IDL.Text,
    'timestamp' : Time,
    'severity' : Severity,
    'location' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'id' : ID,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const SafetyGuideline = IDL.Record({
    'tips' : IDL.Vec(IDL.Text),
    'disasterType' : AlertType,
  });
  const SOSEvent = IDL.Record({
    'id' : ID,
    'timestamp' : Time,
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addDisasterAlert' : IDL.Func(
        [AlertType, Severity, IDL.Text, IDL.Text],
        [ID],
        [],
      ),
    'addEmergencyContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ID], []),
    'deleteDisasterAlert' : IDL.Func([ID], [], []),
    'deleteEmergencyContact' : IDL.Func([ID], [], []),
    'getAllDisasterAlerts' : IDL.Func([], [IDL.Vec(DisasterAlert)], ['query']),
    'getAllEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getAllSafetyGuidelines' : IDL.Func(
        [],
        [IDL.Vec(SafetyGuideline)],
        ['query'],
      ),
    'getRecentSOSEvents' : IDL.Func([IDL.Nat], [IDL.Vec(SOSEvent)], ['query']),
    'getSafetyGuidelinesByType' : IDL.Func(
        [AlertType],
        [SafetyGuideline],
        ['query'],
      ),
    'logSOSEvent' : IDL.Func([IDL.Opt(IDL.Text)], [ID], []),
  });
};

export const init = ({ IDL }) => { return []; };