/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertType = { 'flood' : null } |
  { 'earthquake' : null } |
  { 'fire' : null } |
  { 'tsunami' : null } |
  { 'storm' : null };
export interface DisasterAlert {
  'id' : ID,
  'alertType' : AlertType,
  'message' : string,
  'timestamp' : Time,
  'severity' : Severity,
  'location' : string,
}
export interface EmergencyContact {
  'id' : ID,
  'relationship' : string,
  'name' : string,
  'phoneNumber' : string,
}
export type ID = bigint;
export interface SOSEvent {
  'id' : ID,
  'timestamp' : Time,
  'location' : [] | [string],
}
export interface SafetyGuideline {
  'tips' : Array<string>,
  'disasterType' : AlertType,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface _SERVICE {
  'addDisasterAlert' : ActorMethod<[AlertType, Severity, string, string], ID>,
  'addEmergencyContact' : ActorMethod<[string, string, string], ID>,
  'deleteDisasterAlert' : ActorMethod<[ID], undefined>,
  'deleteEmergencyContact' : ActorMethod<[ID], undefined>,
  'getAllDisasterAlerts' : ActorMethod<[], Array<DisasterAlert>>,
  'getAllEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'getAllSafetyGuidelines' : ActorMethod<[], Array<SafetyGuideline>>,
  'getRecentSOSEvents' : ActorMethod<[bigint], Array<SOSEvent>>,
  'getSafetyGuidelinesByType' : ActorMethod<[AlertType], SafetyGuideline>,
  'logSOSEvent' : ActorMethod<[[] | [string]], ID>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];