/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SafetyGuideline {
    tips: Array<string>;
    disasterType: AlertType;
}
export type Time = bigint;
export interface DisasterAlert {
    id: ID;
    alertType: AlertType;
    message: string;
    timestamp: Time;
    severity: Severity;
    location: string;
}
export interface EmergencyContact {
    id: ID;
    relationship: string;
    name: string;
    phoneNumber: string;
}
export interface SOSEvent {
    id: ID;
    timestamp: Time;
    location?: string;
}
export type ID = bigint;
export enum AlertType {
    flood = "flood",
    earthquake = "earthquake",
    fire = "fire",
    tsunami = "tsunami",
    storm = "storm"
}
export enum Severity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export interface backendInterface {
    addDisasterAlert(alertType: AlertType, severity: Severity, location: string, message: string): Promise<ID>;
    addEmergencyContact(name: string, phoneNumber: string, relationship: string): Promise<ID>;
    deleteDisasterAlert(id: ID): Promise<void>;
    deleteEmergencyContact(id: ID): Promise<void>;
    getAllDisasterAlerts(): Promise<Array<DisasterAlert>>;
    getAllEmergencyContacts(): Promise<Array<EmergencyContact>>;
    getAllSafetyGuidelines(): Promise<Array<SafetyGuideline>>;
    getRecentSOSEvents(limit: bigint): Promise<Array<SOSEvent>>;
    getSafetyGuidelinesByType(disasterType: AlertType): Promise<SafetyGuideline>;
    logSOSEvent(location: string | null): Promise<ID>;
}
import type { AlertType as _AlertType, DisasterAlert as _DisasterAlert, ID as _ID, SOSEvent as _SOSEvent, SafetyGuideline as _SafetyGuideline, Severity as _Severity, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDisasterAlert(arg0: AlertType, arg1: Severity, arg2: string, arg3: string): Promise<ID> {
        if (this.processError) {
            try {
                const result = await this.actor.addDisasterAlert(to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Severity_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDisasterAlert(to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Severity_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addEmergencyContact(arg0: string, arg1: string, arg2: string): Promise<ID> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmergencyContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmergencyContact(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteDisasterAlert(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDisasterAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDisasterAlert(arg0);
            return result;
        }
    }
    async deleteEmergencyContact(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmergencyContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmergencyContact(arg0);
            return result;
        }
    }
    async getAllDisasterAlerts(): Promise<Array<DisasterAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDisasterAlerts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDisasterAlerts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmergencyContacts(): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmergencyContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmergencyContacts();
            return result;
        }
    }
    async getAllSafetyGuidelines(): Promise<Array<SafetyGuideline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSafetyGuidelines();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSafetyGuidelines();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentSOSEvents(arg0: bigint): Promise<Array<SOSEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentSOSEvents(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentSOSEvents(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafetyGuidelinesByType(arg0: AlertType): Promise<SafetyGuideline> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafetyGuidelinesByType(to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SafetyGuideline_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafetyGuidelinesByType(to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SafetyGuideline_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async logSOSEvent(arg0: string | null): Promise<ID> {
        if (this.processError) {
            try {
                const result = await this.actor.logSOSEvent(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSOSEvent(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AlertType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DisasterAlert_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisasterAlert): DisasterAlert {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SOSEvent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SOSEvent): SOSEvent {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SafetyGuideline_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SafetyGuideline): SafetyGuideline {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tips: Array<string>;
    disasterType: _AlertType;
}): {
    tips: Array<string>;
    disasterType: AlertType;
} {
    return {
        tips: value.tips,
        disasterType: from_candid_AlertType_n8(_uploadFile, _downloadFile, value.disasterType)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    timestamp: _Time;
    location: [] | [string];
}): {
    id: ID;
    timestamp: Time;
    location?: string;
} {
    return {
        id: value.id,
        timestamp: value.timestamp,
        location: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    alertType: _AlertType;
    message: string;
    timestamp: _Time;
    severity: _Severity;
    location: string;
}): {
    id: ID;
    alertType: AlertType;
    message: string;
    timestamp: Time;
    severity: Severity;
    location: string;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n8(_uploadFile, _downloadFile, value.alertType),
        message: value.message,
        timestamp: value.timestamp,
        severity: from_candid_Severity_n10(_uploadFile, _downloadFile, value.severity),
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "critical" in value ? Severity.critical : "medium" in value ? Severity.medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flood: null;
} | {
    earthquake: null;
} | {
    fire: null;
} | {
    tsunami: null;
} | {
    storm: null;
}): AlertType {
    return "flood" in value ? AlertType.flood : "earthquake" in value ? AlertType.earthquake : "fire" in value ? AlertType.fire : "tsunami" in value ? AlertType.tsunami : "storm" in value ? AlertType.storm : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SafetyGuideline>): Array<SafetyGuideline> {
    return value.map((x)=>from_candid_SafetyGuideline_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SOSEvent>): Array<SOSEvent> {
    return value.map((x)=>from_candid_SOSEvent_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DisasterAlert>): Array<DisasterAlert> {
    return value.map((x)=>from_candid_DisasterAlert_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AlertType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    flood: null;
} | {
    earthquake: null;
} | {
    fire: null;
} | {
    tsunami: null;
} | {
    storm: null;
} {
    return value == AlertType.flood ? {
        flood: null
    } : value == AlertType.earthquake ? {
        earthquake: null
    } : value == AlertType.fire ? {
        fire: null
    } : value == AlertType.tsunami ? {
        tsunami: null
    } : value == AlertType.storm ? {
        storm: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.critical ? {
        critical: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
